// <auto-generated />
using System;
using CodeSheriff.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeSheriff.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CodeSheriffDbContext))]
    partial class CodeSheriffDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeSheriff.Domain.Entities.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("author_login");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("base_branch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GitHubPrNumber")
                        .HasColumnType("integer")
                        .HasColumnName("github_pr_number");

                    b.Property<string>("HeadBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("head_branch");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "GitHubPrNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_pull_requests_repository_pr_number");

                    b.ToTable("pull_requests", (string)null);
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("clerk_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)")
                        .HasColumnName("full_name");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClerkUserId")
                        .HasDatabaseName("ix_repositories_clerk_user_id");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .HasDatabaseName("ix_repositories_full_name");

                    b.HasIndex("GitHubId")
                        .IsUnique()
                        .HasDatabaseName("ix_repositories_github_id");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ProcessingTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("processing_time_ms");

                    b.Property<Guid>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("RawAiResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_ai_response");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("summary");

                    b.Property<decimal>("TechDebtScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tech_debt_score");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId")
                        .HasDatabaseName("ix_reviews_pull_request_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.ReviewIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_path");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("suggestion");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .HasDatabaseName("ix_review_issues_review_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_review_issues_severity");

                    b.ToTable("review_issues", (string)null);
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.WeeklyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageTechDebtScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("average_tech_debt_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("summary");

                    b.Property<int>("TotalIssues")
                        .HasColumnType("integer")
                        .HasColumnName("total_issues");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("integer")
                        .HasColumnName("total_reviews");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("ix_weekly_reports_repository_id");

                    b.HasIndex("RepositoryId", "PeriodStart")
                        .HasDatabaseName("ix_weekly_reports_repository_period");

                    b.ToTable("weekly_reports", (string)null);
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.PullRequest", b =>
                {
                    b.HasOne("CodeSheriff.Domain.Entities.Repository", "Repository")
                        .WithMany("PullRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.Review", b =>
                {
                    b.HasOne("CodeSheriff.Domain.Entities.PullRequest", "PullRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.ReviewIssue", b =>
                {
                    b.HasOne("CodeSheriff.Domain.Entities.Review", "Review")
                        .WithMany("Issues")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.WeeklyReport", b =>
                {
                    b.HasOne("CodeSheriff.Domain.Entities.Repository", "Repository")
                        .WithMany("WeeklyReports")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.PullRequest", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.Repository", b =>
                {
                    b.Navigation("PullRequests");

                    b.Navigation("WeeklyReports");
                });

            modelBuilder.Entity("CodeSheriff.Domain.Entities.Review", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
